### ISSUE TITLE
Inconsistency in starting sample application on Chromecast

### ISSUE THREAD

**Issue by jjhargreaves** [googlecast/CastHelloText-android#17]
Hi there, I am experiencing issues with consistency with casting this (unmodified) application to a Chromecast. 

Pressing the cast button casts the receiver application to the chromecast, but the sender application does not often receive confirmation from the receiver application that it has started successfully and the caster thinks the casting failed. 

![image](https://cloud.githubusercontent.com/assets/1807207/8024030/24548ccc-0d1c-11e5-9b5c-c021b7ba3270.png)

I have also experienced the very same behavior on the CastHelloText-chrome sample application.

edit: I have tried this on 2 chromecasts on different networks.

**Comment by entertailion** [comment]
Cannot reproduce. Try the latest version of the code.

**Comment by jjhargreaves** [comment]
Tried new version, seems to have fixed :)
