### ISSUE TITLE
Cast button shows an incorrect state when the app is started for the second time

### ISSUE THREAD

**Issue by claudiocherubino** [googlecast/CastHelloText-android#8]
Steps to reproduce:

1. Run Cast Hello Text
2. Connect to a Chromecast device
3. Press the Back button on the sender
4. Run Cast Hello Text again

Expected result: the Chromecast device is disconnected and the Cast button is in the Disconnected state

Actual result: the Chromecast device is disconnected but the Cast button is in the Connected state

**Comment by jjhargreaves** [comment]
I see this issue also.

**Comment by entertailion** [comment]
Fixed
